apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-preferred
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-preferred
  template:
    metadata:
      labels:
        app: nginx-preferred
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                - small

          - weight: 10
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                - medium

      containers:
      - name: nginx
        image: nginx
